### ISSUE TITLE
Use 'wait-for' strategy in Docker-compose all-in-one.yaml 

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-Girl#88]
# Description

Currently we don't harness any 'wait-for' strategy for dependencies in our docker-compose's setup, e.g., the following script is the `submission-service` config in the `all-in-one.yaml` file.

```yaml
depends_on:
      - mongodb
      - rabbitmq
    # Sleep 18 seconds to wait-for its dependencies
    command: "/bin/sh -c 'sleep 18 && java -jar /app.jar'"
```

This issue aims at replacing such unstable sleeping strategy with certain`wait-for` strategy. Which will ping the rabbitmq's until rabbitmq is ready for any incoming client.

# Acceptance Criteria

`all-in-one.yaml` works well.
